/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientServer;
import java.util.ArrayList;
import model.Message;
import model.User;

/**
 *
 * @author hoang
 */
public class ChatForm extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form ChatForm
     */
    private ClientServer clientServer;
    private User userConnected;
    private User receiver;
    private ArrayList<Message> listCurrMessage;

    public ChatForm() {
        initComponents();
    }

    public ChatForm(ClientServer clientServer, User userConnected, User receiver) {
        initComponents();
        this.clientServer = clientServer;
        this.userConnected = userConnected;
        this.receiver = receiver;
        this.listCurrMessage = new ArrayList<>();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Thread t  = new Thread(this);
        t.start();
    }

    @Override
    public void run() {
        setLabelReceiverName();
        while(true){
            displayMsgContent();
            try{
                Thread.sleep(5000);
            }catch(InterruptedException e){
                System.out.println("Can not sleep! "+e);
            }
        }
    }
    private void setLabelReceiverName(){
        lbReceiverName.setText(userConnected.getFullName()+" chat to "+receiver.getFullName());
    }
    private void displayMsgContent() {
        ArrayList<Message> listMessage = clientServer.getMessageFromUser(receiver);
        int numberMsgInCurrMsg = listCurrMessage.size();
        int numberMsgInListMsg = listMessage.size();
        if (numberMsgInCurrMsg < numberMsgInListMsg) {
            for (int i = numberMsgInListMsg - (numberMsgInListMsg - numberMsgInCurrMsg); i < numberMsgInListMsg; i++) {
                areaContent.append(listMessage.get(i).getSender()+":\n\t-"+listMessage.get(i).getContent()+"\n");
            }
        }
        listCurrMessage = listMessage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaContent = new javax.swing.JTextArea();
        lbReceiverName = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        txtContent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaContent.setColumns(20);
        areaContent.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        areaContent.setRows(5);
        jScrollPane1.setViewportView(areaContent);

        lbReceiverName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbReceiverName.setText("jLabel1");

        btSend.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btSend.setText("SEND");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        btExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbReceiverName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtContent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSend))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReceiverName)
                    .addComponent(btExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSend)
                    .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        // TODO add your handling code here:
        String content = txtContent.getText();
        if(content.isEmpty()){
            return;
        }else{
            clientServer.sendMessageToUser(new Message(userConnected.getUserName(), receiver.getUserName(), content));
            txtContent.setText("");
        }
    }//GEN-LAST:event_btSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaContent;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbReceiverName;
    private javax.swing.JTextField txtContent;
    // End of variables declaration//GEN-END:variables
}
